---
name: ROS2 test_build_jazzy

on:
  workflow_dispatch:

  push:
    branches:
      - jazzy
  
  pull_request:
    branches:
      - jazzy

jobs:
  test_build_jazzy:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:jazzy-core
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: jazzy
          skip-tests: false
          rosdep-check: true
          package-name: 'dual_lidar_merger'
          ref: jazzy