pull_request_rules:
  - name: backport patches to the stable branch
    conditions:
      - label = backport
    actions:
      backport:
        branches:
          - "jazzy"
          - "humble"
        assignees:
          - "{{ author }}"