---
name: Rolling build_test

on:
  workflow_dispatch:

  push:
    branches:
      - rolling
  
  pull_request:
    branches:
      - rolling

jobs:
  test_build_rolling:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:rolling-desktop
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: rolling
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: rolling
          skip-tests: false
          rosdep-check: true
          package-name: 'dual_laser_merger'
          ref: rolling
